"""Create the ignored backend .env for local development (Cloud SQL/native-auth mode)."""

import secrets
from pathlib import Path

FRONTEND_DIR = Path("/Users/user/stratsol-projects/Urban-Farming")
FRONTEND_ENV_LOCAL = FRONTEND_DIR / ".env.local"
BACKEND_ENV = Path(__file__).resolve().parents[1] / ".env"


def read_env(path: Path) -> dict[str, str]:
    values: dict[str, str] = {}
    if not path.exists():
        return values
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        values[key.strip()] = value.strip().strip('"').strip("'")
    return values


def main() -> None:
    # .env.local carries the private values (SMTP credentials, admin email).
    source = read_env(FRONTEND_ENV_LOCAL)
    existing = read_env(BACKEND_ENV)
    # Keep the JWT secret stable across regenerations so local sessions survive.
    jwt_secret = existing.get("JWT_SECRET") or secrets.token_urlsafe(48)

    admin_email = source.get("ADMIN_EMAIL", "admin@stratsol.co.za")
    lines = [
        "# Generated by scripts/sync_frontend_env.py. Do not commit.",
        "ENVIRONMENT=development",
        "API_PREFIX=/api/v1",
        "LOG_LEVEL=INFO",
        "ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000,"
        "http://localhost:5173,http://127.0.0.1:5173,"
        "http://localhost:8081,http://127.0.0.1:8081",
        "DATA_BACKEND=postgres",
        "AUTH_MODE=native",
        f"JWT_SECRET={jwt_secret}",
        "# GCP console -> APIs & Services -> Credentials -> OAuth client ID (web)",
        f"GOOGLE_CLIENT_ID={existing.get('GOOGLE_CLIENT_ID', '')}",
        "# Local compose database (run `docker compose up postgres` + `make db-bootstrap`).",
        "DATABASE_URL=postgresql+asyncpg://urban_farming:local-development-only"
        "@127.0.0.1:5432/urban_farming",
        "DB_POOL_SIZE=5",
        "DB_MAX_OVERFLOW=10",
        "STORAGE_BACKEND=gcs",
        "# Inspection photo uploads need this bucket + GCP credentials (ADC).",
        f"GCS_BUCKET={existing.get('GCS_BUCKET', '')}",
        f"GCP_PROJECT_ID={existing.get('GCP_PROJECT_ID', '')}",
        "# Backend email gateway uses STARTTLS, so Gmail must be on 587 (not 465/SSL).",
        f"SMTP_HOST={source.get('SMTP_HOST', '')}",
        "SMTP_PORT=587",
        f"SMTP_USER={source.get('SMTP_USER', '')}",
        f"SMTP_PASSWORD={source.get('SMTP_PASS', '')}",
        f"SMTP_FROM_EMAIL={source.get('SMTP_USER', '')}",
        "SMTP_FROM_NAME=Urban Farming",
        f"ADMIN_EMAIL={admin_email}",
        f"GEOCODING_USER_AGENT=UrbanFarmingPlatform/1.0 ({admin_email})",
        "",
    ]
    BACKEND_ENV.write_text("\n".join(lines), encoding="utf-8")
    BACKEND_ENV.chmod(0o600)
    print(f"Created {BACKEND_ENV} with mode 0600")


if __name__ == "__main__":
    main()
